---
title: Dunedin Gig Archives
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  blog_posts:
    title: Blog
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    parent: Gigs
- scope:
    path: ''
    type: blog_posts
  values:
    permalink: "/blog/:title/"
    layout: blog_post
    type: blog
    parent: Blog
email: fraser@dunedinsound.com
asset_url:
excerpt_separator: "<!-- more -->"
keep_files:
- assets/img
- assets/audio
description: |
  Rare and unofficial recordings of cool local bands since 2014.
baseurl: ''
url: http://dunedinsound.com
permalink: "/gigs/:title/"
exclude: 
- assets/img
- assets/audio
- s3_website.yml
- Gruntfile.js
- package.json
- node_modules
- README.md
- docker
include:
- _pages
- _pages/artists
- _pages/venues
sass:
  style: compressed
markdown: kramdown
gems:
- jemoji
- jekyll-exiftag