---
title: Dunedin Gig Archives | Videos, Photos, Live Bootlegs
timezone: Pacific/Auckland
collections:
  posts:
    title: Posts
    output: true
  blog_posts:
    title: Blog
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: gig
    parent: Gigs
- scope:
    path: ''
    type: blog_posts
  values:
    permalink: "/blog/:title/"
    layout: blog_post
    parent: Blog
    background_color: white
email: fraser@dunedinsound.com
asset_url:
excerpt_separator: "<!-- more -->"
keep_files:
- assets/img
- assets/audio
description: |
  Rare and unofficial bootlegs, photos, and videos of local bands since 2014.
baseurl: ''
url: http://dunedinsound.com
permalink: "/gigs/:title/"
exclude: 
- assets/img
- assets/audio
- s3_website.yml
- Gruntfile.js
- package.json
- package-lock.json
- node_modules
- Gemfile
- README.md
- docker
include:
- _pages
- _pages/artists
- _pages/venues
sass:
  style: compressed
markdown: kramdown
babel_js_extensions: 'es6'
plugins:
- jemoji
- jekyll-babel